
modLoader="javafml"

loaderVersion="[40,)"

license="LGPLv3"

[[mods]]

modId="portal_fluid"

version = "${version}"

displayName="Dimensional Tears"

logoFile="icon.gif"

authors="Ordana"

description='''
Rymes with "fears" or "scares"
'''

[[dependencies.portal_fluid]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.portal_fluid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.portal_fluid]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.12.21,]"
    ordering="AFTER"
    side="BOTH"
