modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/AstralOrdana/dimensional_tears/issues"
license = "LGPLv3"

[[mods]]
modId = "dimensional_tears"
version = "${version}"
displayName = "Dimensional Tears"
authors = "Ordana"
credits="Ordana, cassiancc, axialeaa" #optional
description = '''
Rhymes with "fears" or "scares"
'''
logoFile = "icon.png"

[[dependencies.dimensional_tears]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimensional_tears]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "dimensional_tears.mixins.json"
