@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ordana.dimensional_tears.neoforge.fluid;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;